# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: /home/featurize/data/train_joint.npy
  label_path: /home/featurize/data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: /home/featurize/data/val_joint.npy
  label_path: /home/featurize/data/val_label.npy
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False


# model
model: model.hdgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  num_frame: 300
  graph: graph.uavhd.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 1

#optim
weight_decay: 0.0001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: 0
batch_size: 16
test_batch_size: 16
num_epoch: 65
nesterov: True
warm_up_epoch: 5
